export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const UI_START_LOADING_GALLERY = "UI_START_LOADING_GALLERY";
export const UI_STOP_LOADING_GALLERY = "UI_STOP_LOADING_GALLERY";

export const SET_LIST_PLACE = "SET_LIST_PLACE";
export const SET_GALLERY = "SET_GALLERY";
export const SET_MAP_PINS = "SET_MAP_PINS";
